processed 5 tasks

init:
A: object(100)

task 1 'run'. lines 8-8:
created: object(104)
written: object(103)

task 2 'run'. lines 10-10:
written: object(104), object(105)

task 3 'run'. lines 12-12:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: TypeError, source: Some("Only owned object can be passed by-value, violation found in argument 0") } }

task 4 'run'. lines 14-14:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: TypeError, source: Some("Argument 0 is expected to be mutable, immutable object found") } }
