processed 19 tasks

init:
A: object(100)

task 1 'publish'. lines 8-116:
created: object(105)
written: object(104)

task 2 'run'. lines 118-118:
written: object(106)

task 3 'run'. lines 120-124:
created: object(108)
written: object(107)

task 4 'run'. lines 126-126:
written: object(109)
deleted: object(108)

task 5 'run'. lines 128-128:
created: object(111)
written: object(110)

task 6 'run'. lines 130-130:
created: object(113), object(114)
written: object(111), object(112)

task 7 'run'. lines 132-136:
Error: Object 0x643e4088c9f71f7637e1a3084ad0d4d8b2556f97e448c252b4da755dc5caf220 is owned by object 0x8a45165b87d2b63f05ca24326c378a858f946d7ff998168ab4d2b4e07ad44880. Objects owned by other objects cannot be used as input arguments.

task 8 'run'. lines 138-138:
created: object(117)
written: object(116)

task 9 'run'. lines 140-143:
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }

task 10 'run'. lines 145-145:
created: object(120)
written: object(119)

task 11 'run'. lines 147-147:
created: object(122)
written: object(121)

task 12 'run'. lines 149-152:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(0) } }

task 13 'run'. lines 154-154:
created: object(125)
written: object(124)

task 14 'run'. lines 156-159:
Error: Transaction Effects Status: Invalid command argument at 0. Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue }, source: None, command: Some(0) } }

task 15 'run'. lines 161-161:
created: object(128)
written: object(127)

task 16 'run'. lines 163-166:
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of already taken value. There is now no value available at this location
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidUsageOfTakenValue }, source: None, command: Some(1) } }

task 17 'run'. lines 168-168:
created: object(131)
written: object(130)

task 18 'run'. lines 170-170:
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of already taken value. There is now no value available at this location
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidUsageOfTakenValue }, source: None, command: Some(1) } }
