processed 1 task

task 0 'publish'. lines 4-17:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("_::m::init at offset 1. Cannot call a module's 'init' function from another Move function") } }
